---
title: "Estudiantes en situación de desplazamiento en Santander"
date: "`r Sys.Date()`"
output: 
  html_document:
    theme: journal                # Opciones: default, journal, yeti, cerulean, darkly
    toc: TRUE                     # incluir table of contents (true/false)
    toc_float: TRUE               # toc flotante a la izquierda (true/false)
    number_sections: TRUE         # numerar secciones y subsecciones (true/false)
    code_folding: show            # por defecto el código aparecerá oculto: show/hide
lang: es-ES
bibliography: refs.bib
csl: apa.csl
---

# Introducción
El desplazamiento forzado en Colombia, a causa del conflicto armado, ha afectado a más de seis millones de personas en los últimos treinta años, pero. Estas personas y familias obligadas a huir de sus hogares deben reacomodarse en la sociedad donde fueron a parar y uno de los aspectos mas importantes en este proceso es la educación, puesto que es un derecho social fundamental. A partir de esto surgen cuestiones sobre ¿cuáles causas de desplazamiento son las más comunes?, ¿qué tipo de educación reciben las personas en esta situación?, todo esto según su ubicación actual, edad, género u otros aspectos característicos de cada individuo.

Con la intención de conocer esta información y dar a entender de una manera general y más sencilla la situación de los estudiantes desplazados en el departamento de Santander, se planean usar los datos proporcionados por el estado colombiano para el año 2022. Para responder a las preguntas generadas, se generarán las medidas estadísticas pertinentes con la ayuda de R y se explicarán los conceptos presentes en el conjunto de datos.

# Paquetes de R requeridos
```{r, eval=FALSE}
library(readxl)
library(tidyverse)
library(writexl)
library(skimr)
library(vembedr)
```

# Preparación de los datos


# Análisis exploratorio de datos


# Conclusiones

# Bibliografía
@_2022_estudiantes
@_2015_una
@_desplazamiento